/*--------------------------------------------------------------------------#
#  Jenkins running on remote EC2 AWS instance, remote webserver too         #
#  Need to install ssh plugins                                              #
#  Edit jenkins configuration to add remote server and ssh key              #
#  Its better to set "/" directory and define declaratively                 #
#  Create new pipeline, choose SCM using https                              #
#                                                                           #
#  Select "Script path" in git repo /jenkins/docker_php_deploy/Jenkinsfile  #
#                                                                           #
#  Update date:        01.06.2023                                           #
#--------------------------------------------------------------------------*/
pipeline {
    agent { label 'slave-1' }
    environment {
        CI_IMAGE_NAME = 'web_container'
        CI_CONTAINER_NAME = 'test_container'
        CONTAINER_EXTERNAL_PORT = '8080'
        CD_IMAGE_REPO_USER = 'wood8'
        CD_IMAGE_NAME_VERSION = 'jenkins-cicd'
    }

    options {
        skipDefaultCheckout()
        timestamps()
    }

    stages {
        stage('Delete workspace before build starts') {
            steps {
                echo 'Deleting workspace dir'
                deleteDir()
            //sh 'ls -la'
            //sh 'pwd'
            }
        }

        stage('Checkout') {
            steps {
                git(
                    url: 'https://github.com/gitwood8/jenkins-deploy-webpage.git',
                    branch: 'main'
                )
            }
        }

//        stage('test ls') {
//            steps {
//                dir('jenkins/docker_php_deploy/') {
//                    sh "ls -la"
//                    sh "pwd"
//                }
//                    //dir inside workspace on slave
//                    sh "ls -la"
//                    sh "pwd"
//            }
//        }

        stage('Build docker image') {
            steps {
                dir('jenkins/docker_php_deploy/docker/') {
                    sh "docker build -t ${env.CI_IMAGE_NAME} ."
                    sh "docker run -d --rm --name ${env.CI_CONTAINER_NAME} -p ${env.CONTAINER_EXTERNAL_PORT}:80 ${env.CI_IMAGE_NAME}"
                    sleep 20
                    sh "docker inspect --format='{{json .State.Health}}' \$(docker ps -q) | grep '\"Status\":\"healthy\"'"
                    sh 'curl ifconfig.me'
                    sleep 10
                    sh 'docker ps -qa | xargs docker stop'
                    //sh "for i in \$(docker images -qa); do docker rmi \$i 2>/dev/null; done"
                    sh 'docker images -q | xargs docker rmi 2>/dev/null'
                }
            }
        }
    }
}
